name: movie_mania
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.1.0
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.11.0
  http: ^1.3.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  height: 200
  width: 200
  min_sdk_android: 23
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/guestuser.png
  fonts:
    - family: oldeng
      fonts:
      - asset: assets/fonts/OLDENGL.ttf
    - family: showg
      fonts:
      - asset: assets/fonts/SHOWG.ttf

