name: movie_mania
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.1.0
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
  fonts:
    - family: oldeng
      fonts:
      - asset: assets/fonts/OLDENGL.ttf
    - family: showg
      fonts:
      - asset: assets/fonts/SHOWG.ttf

